/*  =========================================================================
    fty_exdialogue_classes - private header file

    Copyright (C) 2014 - 2017 Eaton

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef FTY_EXDIALOGUE_CLASSES_H_INCLUDED
#define FTY_EXDIALOGUE_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/fty_exdialogue.h"

//  Extra headers

//  Opaque class structures to allow forward references

//WA issue #4 "Message "Invalid argument (src/mutex.hpp:142)"
//see https://github.com/eaton-bob/nestor/issues/4
//comment the line below to disable WA
#define WORKAROUND_ISSUE4

//  Internal API


//  *** To avoid double-definitions, only define if building without draft ***
#ifndef FTY_EXDIALOGUE_BUILD_DRAFT_API

//  Self test for private classes
FTY_EXDIALOGUE_PRIVATE void
    fty_exdialogue_private_selftest (bool verbose, const char *subtest);

#endif // FTY_EXDIALOGUE_BUILD_DRAFT_API

#endif
